### PR TITLE
i168-improve-language-switcher

### PR DESCRIPTION
**Pull request by kgosal03**
Language switcher is working as desired now. It stays on the same page after changing language.

### CODE REVIEW

**Comment by kgosal03** [comment]
@ghjensen  I have added this code for now. I think I need to get an account for the test server from Matthew. Also what flow do you guys like, as mentioned in the readme.md or the test server one?

**Comment by ghjensen** [comment]
Hey @kgosal03. Thanks for this! I've just merged the code and will test it out shortly.

As for workflow: I think you can follow the workflow mentioned in the readme.md, but that also includes doing tests on the test server as well (since the changes should be available for testing at test.hsscommons.ca once they've been merged into the h2.2.22 branch). Does that answer your question, or did I miss anything?

**Comment by kgosal03** [comment]
Sounds good! Sure, I tested it a little on the test server after your email
and it is working as expected. Hopefully it will be good to go after you
test it.

**Comment by ghjensen** [comment]
It looks good to me, too! Thanks, Karan. I'll send an update request to UVic so that we can see it on the production server. :)

**Pull request merged**
